# -*- coding: utf-8 -*-
"""EDA on NETFLIX Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BfYpmJEkHdO30SF_v_abLVOl4jTk1-b
"""

#Importing Necessary Libraries for EDA
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#importing data into the environment
data = pd.read_csv('data.csv')

#Basic Info
# Show top rows
print(data.head())

# Overview of the dataset
print(data.info())

# Summary statistics (including categorical data)
print(data.describe(include='all'))

# Check for missing values
print(data.isnull().sum())

#drop unnecessary columns ('availableCountries' in this case as 99% of the rows there are missing)
data = data.drop(columns=['availableCountries'])

#Univariate Analysis

#Showing the count of movies vs tv shows
sns.countplot(x='type', data=data)
plt.title('Count of Content Type: Movies vs TV Shows')
plt.show()

#Top 10 genres
data['genres'].str.split(', ').explode().value_counts().head(10).plot(kind='bar')
plt.title('Top 10 Genres')
plt.ylabel('Count')
plt.show()

# Distribution of IMDb Ratings
sns.histplot(data['imdbAverageRating'], bins=20, kde=True)
plt.title('Distribution of IMDb Ratings')
plt.show()

# Votes vs Ratings
sns.scatterplot(x='imdbNumVotes', y='imdbAverageRating', data=data)
plt.title('IMDb Votes vs Ratings')
plt.show()

# Content count by release year
sns.histplot(data['releaseYear'].dropna(), bins=30, kde=False)
plt.title('Content Released Over the Years')
plt.xlabel('Release Year')
plt.ylabel('Number of Titles')
plt.show()

# Average rating by year
data.groupby('releaseYear')['imdbAverageRating'].mean().plot()
plt.title('Average IMDb Rating by Release Year')
plt.ylabel('Average Rating')
plt.show()